### ISSUE TITLE
Linking Error when building for iOS

### ISSUE THREAD

**Issue by Zack-Xb** [lightsing/tid-rs#2]
I am building a mobile app using tauri mobile and I'm trying to integrate the localauthentication framework into it. On mac this is working but when building for ios I get this error.

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_LAContext", referenced from:
      objc-class-ref in libavailx_lib.a(tid.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any idea of how to resolve this?

**Comment by lightsing** [comment]
Thank you for reaching out regarding this issue. but sorry for that, I'm not an iOS developer and not even use ObjectiveC/Swift.

**Comment by Zack-Xb** [comment]
It's fine thanks for developing this, I think it has to do the LocalAuthentication library not being linked well when targeting ios hence undefined LAContext. I changed the build.rs to use `cc-rs` as it was not working for me before. Maybe the problem stems from here.

**Comment by Zack-Xb** [comment]
Link LocalAuthentication framework from xcode and build again. This then works fine on iOS.
